# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.2
source:
  patches: null
  sha256: f7de13462f7a82c29ab865820149e778cbfe01087b3a55b5332707abf9db4a6e
  url: https://github.com/facebook/zstd/archive/v1.5.2.tar.gz
build:
  number: 6
  run_exports:
    - zstd >=1.5.2,<1.6.0a0
  string: hf913c23_6
requirements:
  build:
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_11
    - cctools_osx-arm64 973.0.1 hfd1dfa6_11
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_4
    - clangxx 14.0.6 default_h55ffa42_0
    - clangxx_osx-arm64 14.0.6 h748fd88_4
    - cmake-no-system 3.16.5 he49afe7_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - ld64_osx-64 609 hfd63004_11
    - ld64_osx-arm64 609 h566df06_11
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 14.0.6 hccf4f1f_0
    - libllvm14 14.0.6 h5b596cc_1
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - make 4.3 h22f3db7_1
    - ninja 1.11.0 h1b54a9f_0
    - openssl 3.0.7 hfd90126_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - libcxx 14.0.6 h2692d47_0
    - libzlib 1.2.13 h03a7124_4
    - zlib 1.2.13 h03a7124_4
  run:
    - libcxx >=14.0.6
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libzstd.dylib
    - test ! -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/include/zstd.h
    - zstd -be -i5
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - pkg-config --cflags libzstd
    - cd cf_test
  files:
    - cf_test/
  requires:
    - clang_osx-arm64 14.*
    - cmake
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  feedstock-name: zstd
  final: true
  recipe-maintainers:
    - hmaarrfk
    - msarahan
    - rmax
    - xhochy
