# This file created by conda-build 3.23.3
# ------------------------------------------------

package:
  name: libcurl
  version: 7.88.1
source:
  sha256: 8224b45cce12abde039c12dc0711b7ea85b104b9ad534d6e4c5b4e188a61c907
  url: http://curl.haxx.se/download/curl-7.88.1.tar.bz2
build:
  number: 1
  run_exports:
    - libcurl >=7.88.1,<8.0a0
  string: h9049daf_1
requirements:
  build:
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 h48a5a9d_12
    - cctools_osx-arm64 973.0.1 hd9287c6_12
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_5
    - clangxx 14.0.6 default_h55ffa42_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - icu 70.1 h96cf925_0
    - ld64_osx-64 609 hfd63004_12
    - ld64_osx-arm64 609 h566df06_12
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 15.0.7 h71dddab_0
    - libiconv 1.17 hac89ed1_0
    - libllvm14 14.0.6 h5b596cc_1
    - libllvm15 15.0.7 h7001e86_1
    - libxml2 2.10.3 hb9e07b5_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - openssl 3.1.0 hfd90126_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - c-ares 1.18.1 h3422bc3_0
    - ca-certificates 2022.12.7 h4653dfc_0
    - krb5 1.20.1 h69eda48_0
    - libcxx 15.0.7 h75e25f2_0
    - libedit 3.1.20191231 hc8eb9b7_2
    - libev 4.33 h642e427_1
    - libnghttp2 1.52.0 hae82a92_0
    - libssh2 1.10.0 h7a5bd25_3
    - libzlib 1.2.13 h03a7124_4
    - ncurses 6.3 h07bb92c_1
    - openssl 3.1.0 h03a7124_0
    - zlib 1.2.13 h03a7124_4
    - zstd 1.5.2 hf913c23_6
  run:
    - krb5 >=1.20.1,<1.21.0a0
    - libnghttp2 >=1.52.0,<2.0a0
    - libssh2 >=1.10.0,<2.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - openssl >=3.1.0,<4.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
    - if ! echo $CURL_SSL_BACKENDS | grep -q "Secure Transport"; then exit 1; fi
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs
  doc_url: https://curl.haxx.se/docs/
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
