# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Mar  8 10:55:08 2023
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.17.21
source:
  sha256: 8b7ce697a2f212752a35c1ac414471dc16c424c9573be4926b56ff3f5d23b7af
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.17.21.tar.gz
build:
  number: '3'
  script: /Users/runner/miniforge3/conda-bld/ruamel.yaml_1678273098088/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . --no-deps -vv
  string: py310h8e9501a_3
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_11
    - cctools_osx-arm64 973.0.1 hfd1dfa6_11
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_4
    - clangxx 14.0.6 default_h55ffa42_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - cross-python_osx-arm64 3.10 35_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - ld64_osx-64 609 hfd63004_11
    - ld64_osx-arm64 609 h566df06_11
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 15.0.7 h71dddab_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm14 14.0.6 h5b596cc_1
    - libsqlite 3.40.0 ha978bb4_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.8 hfd90126_0
    - popt 1.16 h7b079dc_2002
    - python 3.10.9 he7542f4_0_cpython
    - readline 8.1.2 h3899abd_0
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022g h191b570_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.12.7 h4653dfc_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.40.0 h76d750c_0
    - libzlib 1.2.13 h03a7124_4
    - ncurses 6.3 h07bb92c_1
    - openssl 3.0.8 h03a7124_0
    - pip 23.0.1 pyhd8ed1ab_0
    - python 3.10.9 h3ba56d0_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.1.2 h46ed386_0
    - ruamel 1.0 py310hbe9552e_7
    - setuptools 67.5.1 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
    - ruamel.yaml.clib >=0.1.2
    - setuptools
test:
  imports:
    - ruamel.yaml
about:
  home: https://sourceforge.net/p/ruamel-yaml
  license: MIT
  license_file: LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - davidbrochart
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
    - xhochy
