# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.40.0
source:
  patches: null
  sha256: 0333552076d2700c75352256e91c78bf5cd62491589ba0c69aed0a81868980e7
  url: https://www.sqlite.org/2022/sqlite-autoconf-3400000.tar.gz
build:
  number: 0
  run_exports:
    - libsqlite >=3.40.0,<4.0a0
  string: h76d750c_0
requirements:
  build:
    - ca-certificates 2022.9.24 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_3
    - clangxx 14.0.6 default_h55ffa42_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - ld64_osx-64 609 h1e06c2b_10
    - ld64_osx-arm64 609 h52af8cb_10
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 14.0.6 hccf4f1f_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.6 h5b596cc_1
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - make 4.3 h22f3db7_1
    - openssl 3.0.7 hfd90126_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - libzlib 1.2.13 h03a7124_4
    - zlib 1.2.13 h03a7124_4
  run:
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - snorfalorpagus
