# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: cryptography
  version: 40.0.1
source:
  sha256: 1be6b818f81d38175fa8a1432c1c5337af6c3653f2912dd85fdfdc5cda7674e4
  url: https://github.com/pyca/cryptography/archive/refs/tags/40.0.1.tar.gz
build:
  number: 0
  script:
    - export OPENSSL_DIR=$PREFIX
    - python -m pip install . -vv
  string: py310hfc83b78_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_13
    - cctools_osx-arm64 973.0.1 hfd1dfa6_13
    - cffi 1.15.1 py310ha78151a_3
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_5
    - clangxx 14.0.6 default_h55ffa42_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - cross-python_osx-arm64 3.10 38_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - ld64_osx-64 609 hfd63004_13
    - ld64_osx-arm64 609 h566df06_13
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 15.0.7 h71dddab_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm14 14.0.6 h5b596cc_1
    - libsqlite 3.40.0 ha978bb4_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.3 h96cf925_1
    - openssl 3.1.0 hfd90126_0
    - popt 1.16 h7b079dc_2002
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.10 he7542f4_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h9e318b2_1
    - rsync 3.2.7 h30d983d_0
    - rust 1.65.0 h7e1429e_0
    - rust-std-aarch64-apple-darwin 1.65.0 hf1a8007_0
    - rust-std-x86_64-apple-darwin 1.65.0 h059895a_0
    - rust_osx-arm64 1.65.0 hc6420c1_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2023b h71feb2d_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.12.7 h4653dfc_0
    - cffi 1.15.1 py310h2399d43_3
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.40.0 h76d750c_0
    - libzlib 1.2.13 h03a7124_4
    - ncurses 6.3 h07bb92c_1
    - openssl 3.1.0 h03a7124_0
    - pip 23.0.1 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.10 h3ba56d0_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.2 h92ec313_1
    - semantic_version 2.10.0 pyhd8ed1ab_0
    - setuptools 67.6.0 pyhd8ed1ab_0
    - setuptools-rust 1.5.2 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - typing_extensions 4.5.0 pyha770c72_0
    - tzdata 2023b h71feb2d_0
    - wheel 0.40.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - cffi >=1.12
    - openssl >=3.1.0,<4.0a0
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
test:
  commands:
    - pytest
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors 40.0.1.*
    - hypothesis
    - iso8601
    - pretend
    - pytest
    - pytest-benchmark
    - pytest-subtests
    - pytz
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces

    to common cryptographic algorithms such as symmetric ciphers, message

    digests, and key derivation functions..

    '
  dev_url: https://github.com/pyca/cryptography
  doc_source_url: https://github.com/pyca/cryptography/blob/main/docs/index.rst
  doc_url: https://cryptography.io/en/latest
  home: https://cryptography.io
  license: Apache-2.0 AND BSD-3-Clause AND PSF-2.0 AND MIT
  license_family: BSD
  license_file: LICENSE
  summary: cryptography is a package designed to expose cryptographic primitives and
    recipes to Python developers.
extra:
  copy_test_source_files: true
  feedstock-name: cryptography
  final: true
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - ocefpaf
