# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Feb 24 18:54:50 2023
# ------------------------------------------------

package:
  name: conda
  version: 23.1.0
source:
  fn: conda-23.1.0.tar.gz
  sha256: ba417f2e77806be36ab99a7640262b263a2dc809398d9403ea5f6f8f14dcc1a8
  url: https://github.com/conda/conda/archive/23.1.0.tar.gz
build:
  always_include_files:
    - bin/activate
    - bin/conda
    - bin/deactivate
  number: '0'
  string: py310hbe9552e_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_11
    - cctools_osx-arm64 973.0.1 hfd1dfa6_11
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_4
    - clangxx 14.0.6 default_h55ffa42_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - cross-python_osx-arm64 3.10 35_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.21.1 h8a4c099_0
    - ld64_osx-64 609 hfd63004_11
    - ld64_osx-arm64 609 h566df06_11
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcxx 14.0.6 hccf4f1f_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.17 hac89ed1_0
    - libllvm14 14.0.6 h5b596cc_1
    - libsqlite 3.40.0 ha978bb4_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.8 hfd90126_0
    - popt 1.16 h7b079dc_2002
    - python 3.10.9 he7542f4_0_cpython
    - readline 8.1.2 h3899abd_0
    - rsync 3.2.7 h30d983d_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022g h191b570_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.2 hbc0c0cd_6
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2022.12.7 h4653dfc_0
    - cffi 1.15.1 py310h2399d43_3
    - colorama 0.4.6 pyhd8ed1ab_0
    - conda-package-handling 2.0.2 pyh38be061_0
    - conda-package-streaming 0.7.0 pyhd8ed1ab_1
    - libcxx 14.0.6 h2692d47_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.40.0 h76d750c_0
    - libzlib 1.2.13 h03a7124_4
    - ncurses 6.3 h07bb92c_1
    - openssl 3.0.8 h03a7124_0
    - pip 23.0.1 pyhd8ed1ab_0
    - pluggy 1.0.0 pyhd8ed1ab_5
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.10.9 h3ba56d0_0_cpython
    - python_abi 3.10 3_cp310
    - readline 8.1.2 h46ed386_0
    - ruamel.yaml 0.17.21 py310h8e9501a_2
    - ruamel.yaml.clib 0.2.7 py310h8e9501a_1
    - setuptools 67.4.0 pyhd8ed1ab_0
    - tk 8.6.12 he1e0b03_0
    - toolz 0.12.0 pyhd8ed1ab_0
    - tqdm 4.64.1 pyhd8ed1ab_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
    - zstandard 0.19.0 py310had9512b_1
    - zstd 1.5.2 hf913c23_6
  run:
    - conda-package-handling >=1.3.0
    - pluggy >=1.0.0
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - python >=3.10,<3.11.0a0
    - python >=3.10,<3.11.0a0 *_cpython
    - python_abi 3.10.* *_cp310
    - requests >=2.20.1,<3
    - ruamel.yaml >=0.11.14,<0.18
    - setuptools >=31.0.1
    - toolz >=0.8.1
    - tqdm >=4
  run_constrained:
    - conda-build >=3
    - conda-content-trust >=0.1.1
    - conda-env >=2.6
    - conda-libmamba-solver >=22.12.0
    - cytoolz >=0.8.1
test:
  commands:
    - env run_pytest=no bash test_runner.sh
  downstreams:
    - conda-smithy
  files:
    - commands_to_test.sh
    - test_runner.sh
  imports:
    - conda
    - conda_env
  requires:
    - mock
    - pexpect
    - responses
about:
  description: 'Conda is an open source package management system and environment
    management system for installing multiple versions of software packages and their
    dependencies and switching easily between them. It works on Linux, OS X and Windows,
    and was created for Python programs but can package and distribute any software.

    '
  dev_url: https://github.com/conda/conda
  doc_url: https://docs.conda.io/projects/conda/en/stable/
  home: https://conda.io
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - jezdez
    - kalefranz
    - mbargull
    - mingwandroid
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
