# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: libssh2
  version: 1.10.0
source:
  patches:
    - 246c7cb0184b9e1a882c753b412825799c7a9118.patch
  sha256: 2d64e90f3ded394b91d3a2e774ca203a4179f69aebee03003e5a6fa621e41d51
  url: https://www.libssh2.org/download/libssh2-1.10.0.tar.gz
build:
  number: 3
  run_exports:
    - libssh2 >=1.10.0,<2.0a0
  string: h7a5bd25_3
requirements:
  build:
    - ca-certificates 2022.6.15 h033912b_0
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang_bootstrap_osx-arm64 11.1.0 h169cfcd_7
    - cmake-no-system 3.16.5 he49afe7_0
    - ld64_osx-arm64 609 h52af8cb_10
    - libcxx 14.0.6 hce7ea42_0
    - libllvm14 14.0.6 h41df66c_0
    - libzlib 1.2.12 hfe4f2af_2
    - make 4.3 h22f3db7_1
    - openssl 3.0.5 hb81d4ab_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host:
    - ca-certificates 2022.6.15 h4653dfc_0
    - libzlib 1.2.12 ha287fd2_2
    - openssl 3.0.5 h7aea29f_1
    - zlib 1.2.12 ha287fd2_2
  run:
    - libzlib >=1.2.12,<1.3.0a0
    - openssl >=3.0.5,<4.0a0
test:
  commands:
    - test -f $PREFIX/include/libssh2.h
    - test -f $PREFIX/include/libssh2_publickey.h
    - test -f $PREFIX/include/libssh2_sftp.h
    - test ! -f $PREFIX/lib/libssh2.a
    - test -f $PREFIX/lib/libssh2${SHLIB_EXT}
about:
  description: 'libssh2 is a library implementing the SSH2 protocol, available under
    the revised BSD license.

    '
  dev_url: https://github.com/libssh2/libssh2
  home: https://www.libssh2.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: the SSH library
extra:
  copy_test_source_files: true
  feedstock-name: libssh2
  final: true
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
    - shadowwalkersb
    - xhochy
