# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Mar  4 16:53:07 2023
# ------------------------------------------------

package:
  name: tqdm
  version: 4.65.0
source:
  sha256: 1871fb68a86b8fb3b59ca4cdd3dcccbc7e6d613eeed31f4c332531977b89beb5
  url: https://pypi.io/packages/source/t/tqdm/tqdm-4.65.0.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.12.7 ha878542_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.8 h0b41bf4_0
    - packaging 23.0 pyhd8ed1ab_0
    - pip 23.0.1 pyhd8ed1ab_0
    - python 3.11.0 he550d4f_1_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 67.4.0 pyhd8ed1ab_0
    - setuptools-scm 7.1.0 pyhd8ed1ab_0
    - setuptools_scm 7.1.0 hd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - toml 0.10.2 pyhd8ed1ab_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.4.0 hd8ed1ab_0
    - typing_extensions 4.4.0 pyha770c72_0
    - tzdata 2022g h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - colorama
    - python >=3.7
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v
    - pytest -k "not tests_perf"
  imports:
    - tqdm
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-timeout
  source_files:
    - pyproject.toml
    - setup.cfg
    - tests
about:
  dev_url: https://tqdm.github.io/docs/tqdm
  doc_source_url: https://github.com/tqdm/tqdm/blob/master/README.rst
  doc_url: https://github.com/tqdm/tqdm#tqdm
  home: https://pypi.python.org/pypi/tqdm
  license: MPL-2.0 or MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - casperdcl
    - ericdill
    - pmlandwehr
