# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Dec 14 22:01:29 2022
# ------------------------------------------------

package:
  name: libsolv
  version: 0.7.23
source:
  fn: libsolv-0.7.23.tar.gz
  patches:
    - conda_variant_priorization.patch
  sha256: 0286155964373c6cc3802d025750786c3ee79608d5cb884598e110e3918bb2fe
  url: https://github.com/openSUSE/libsolv/archive/0.7.23.tar.gz
build:
  number: '0'
  run_exports:
    - libsolv >=0.7.23,<0.8.0a0
  string: hb5ab8b9_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - c-ares 1.18.1 h0d85af4_0
    - ca-certificates 2022.12.7 h033912b_0
    - cctools_osx-64 973.0.1 hcc6d90d_11
    - cctools_osx-arm64 973.0.1 hfd1dfa6_11
    - clang 14.0.6 h694c41f_0
    - clang-14 14.0.6 default_h55ffa42_0
    - clang_osx-arm64 14.0.6 he41d1a2_4
    - clangxx 14.0.6 default_h55ffa42_0
    - clangxx_osx-arm64 14.0.6 h748fd88_4
    - cmake 3.25.1 h4032537_0
    - compiler-rt 14.0.6 h613da45_0
    - compiler-rt_osx-64 14.0.6 hab78ec2_0
    - expat 2.5.0 hf0c8a7f_0
    - krb5 1.19.3 hb98e516_0
    - ld64_osx-64 609 hfd63004_11
    - ld64_osx-arm64 609 h566df06_11
    - libclang-cpp14 14.0.6 default_h55ffa42_0
    - libcurl 7.86.0 h581aaea_1
    - libcxx 14.0.6 hccf4f1f_0
    - libedit 3.1.20191231 h0678c8f_2
    - libev 4.33 haf1e3a3_1
    - libllvm14 14.0.6 h5b596cc_1
    - libnghttp2 1.47.0 h5aae05b_1
    - libssh2 1.10.0 h47af595_3
    - libuv 1.44.2 hac89ed1_0
    - libzlib 1.2.13 hfd90126_4
    - llvm-tools 14.0.6 h5b596cc_1
    - make 4.3 h22f3db7_1
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.7 hfd90126_1
    - rhash 1.4.3 hac89ed1_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zlib 1.2.13 hfd90126_4
    - zstd 1.5.2 hfa58983_4
  host:
    - libcxx 14.0.6 h2692d47_0
    - libzlib 1.2.13 h03a7124_4
    - zlib 1.2.13 h03a7124_4
  run:
    - libcxx >=14.0.6
    - libzlib >=1.2.13,<1.3.0a0
about:
  description: libsolv, a free package dependency solver using a satisfiability algorithm.
  dev_url: https://github.com/openSUSE/libsolv
  home: https://github.com/openSUSE/libsolv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.BSD
  summary: Library for solving packages and reading repositories
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - davidbrochart
    - wolfv
