# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Nov 29 14:54:40 2022
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.7.0
source:
  sha256: 87be2b1c365a0e04d15579b9137b139f0837c52198bdba21c5ac071fc13efd75
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.7.0.tar.gz
build:
  noarch: python
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/conda-package-streaming_1669733752472/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install --no-build-isolation . -vv
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.9.24 ha878542_0
    - flit-core 3.8.0 pyhd8ed1ab_0
    - ld_impl_linux-64 2.39 hcc3a1bd_1
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.2.0 h65d4601_19
    - libgomp 12.2.0 h65d4601_19
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.40.0 h753d276_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.13 h166bdaf_4
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.7 h166bdaf_0
    - pip 22.3.1 pyhd8ed1ab_0
    - python 3.11.0 ha86cf86_0_cpython
    - readline 8.1.2 h0f457ee_0
    - setuptools 65.5.1 pyhd8ed1ab_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022f h191b570_0
    - wheel 0.38.4 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.7
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming.url
  requires:
    - pip
    - requests
about:
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Download metadata from conda packages without transferring entire file.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dholth
